name = "jlFHE"
uuid = "450a7e1a-f93d-11e9-2a6c-7f2e11afe043"
authors = ["Kotaro MATSUOKA"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
